// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-matches.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function db(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_matches_default = defineTool({
  name: "list_matches",
  title: "List matches",
  description: "List the team's recent CS2 matches (map, rival, score, date, type). Most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many matches to return (max 50)."),
    match_type: z.enum(["OFFICIAL", "TRAINING"]).optional().describe("Filter by match type.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, match_type }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = db(ctx).from("matches").select("id, date, map, rival, score_us, score_them, type, starting_side").order("date", { ascending: false }).limit(limit);
    if (match_type) query = query.eq("type", match_type);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-match-stats.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_match_stats_default = defineTool2({
  name: "get_match_stats",
  title: "Get match stats",
  description: "Get one match with per-player stats (kills, deaths, ADR, KAST, rating).",
  inputSchema: {
    match_id: z2.string().uuid().describe("The match UUID (from list_matches).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ match_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = db2(ctx);
    const [{ data: match, error: matchErr }, { data: stats, error: statsErr }] = await Promise.all([
      client.from("matches").select(
        "id, date, map, rival, score_us, score_them, type, starting_side, notes"
      ).eq("id", match_id).maybeSingle(),
      client.from("player_stats").select(
        "steam_tag, kills, deaths, assists, adr, hs_pct, kast_pct, rating, fk, fd"
      ).eq("match_id", match_id)
    ]);
    const err = matchErr ?? statsErr;
    if (err) return { content: [{ type: "text", text: err.message }], isError: true };
    if (!match)
      return { content: [{ type: "text", text: "Match not found" }], isError: true };
    const payload = { match, players: stats ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-upcoming-events.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_upcoming_events_default = defineTool3({
  name: "list_upcoming_events",
  title: "List upcoming agenda events",
  description: "List upcoming training sessions, tacticals, and team events from the agenda.",
  inputSchema: {
    days_ahead: z3.number().int().min(1).max(90).default(14).describe("How many days into the future to look.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ days_ahead }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const end = new Date(Date.now() + days_ahead * 864e5).toISOString().slice(0, 10);
    const { data, error } = await db3(ctx).from("agenda_events").select("id, date, time_start, time_end, title, description, event_type").gte("date", today).lte("date", end).order("date", { ascending: true }).order("time_start", { ascending: true });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-team-members.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_team_members_default = defineTool4({
  name: "list_team_members",
  title: "List team members",
  description: "List the current CS2 roster (player name, steam tag, role, whether they're a coach).",
  inputSchema: {
    include_coaches: z4.boolean().default(true).describe("Include coaches in the result.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ include_coaches }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = db4(ctx).from("team_members").select("player_name, steam_tag, role_in_team, is_coach, steam_id");
    if (!include_coaches) query = query.eq("is_coach", false);
    const { data, error } = await query.order("is_coach", { ascending: true });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { members: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-agenda-event.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
function db5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_agenda_event_default = defineTool5({
  name: "create_agenda_event",
  title: "Create agenda event",
  description: "Add a new event to the team agenda (training, tactical, match, meeting). Requires user approval.",
  inputSchema: {
    title: z5.string().trim().min(1).describe("Event title."),
    date: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Date in YYYY-MM-DD (team local time)."),
    time_start: z5.string().regex(/^\d{2}:\d{2}$/).describe("Start time HH:MM (24h)."),
    time_end: z5.string().regex(/^\d{2}:\d{2}$/).describe("End time HH:MM (24h)."),
    event_type: z5.enum(["training", "tactical", "match", "meeting", "other"]).default("training"),
    description: z5.string().default("")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db5(ctx).from("agenda_events").insert({
      title: input.title,
      date: input.date,
      time_start: input.time_start,
      time_end: input.time_end,
      event_type: input.event_type,
      description: input.description,
      created_by: ctx.getUserId()
    }).select("id, title, date, time_start, time_end, event_type").single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created event ${data.id}` }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pltlrmyzqiitsxggxven";
var mcp_default = defineMcp({
  name: "tacticaltracker-mcp",
  title: "TacticalTracker (Tactical Chaos)",
  version: "0.1.0",
  instructions: "Tools for the Tactical Chaos CS2 team tracker. Use `list_matches` to browse recent matches, `get_match_stats` for per-player breakdowns, `list_team_members` for the roster, `list_upcoming_events` for the agenda, and `create_agenda_event` to schedule a new training/tactical.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_matches_default,
    get_match_stats_default,
    list_upcoming_events_default,
    list_team_members_default,
    create_agenda_event_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
